function [methodinfo,structs,enuminfo,ThunkLibName]=kernel32_m
%KERNEL32_M Create structures to define interfaces found in 'Windows'.

%This function was generated by loadlibrary.m parser version  on Thu Jun 29 11:31:21 2017
%perl options:'Windows.i -outfile=kernel32_m.m -thunkfile=kernel32_thunk_pcwin64.c -header=Windows.h'
ival={cell(1,0)}; % change 0 to the actual number of functions to preallocate the data.
structs=[];enuminfo=[];fcnNum=1;
fcns=struct('name',ival,'calltype',ival,'LHS',ival,'RHS',ival,'alias',ival,'thunkname', ival);
MfilePath=fileparts(mfilename('fullpath'));
ThunkLibName=fullfile(MfilePath,'kernel32_thunk_pcwin64');
methodinfo=fcns;