function [methodinfo,structs,enuminfo,ThunkLibName]=loadkernel_ctr2
%LOADKERNEL_CTR2 Create structures to define interfaces found in 'win_edited_ctr2'.

%This function was generated by loadlibrary.m parser version  on Thu Jun 29 14:05:33 2017
%perl options:'win_edited_ctr2.i -outfile=loadkernel_ctr2.m -thunkfile=kernel32_thunk_pcwin64.c -header=win_edited_ctr2.h'
ival={cell(1,0)}; % change 0 to the actual number of functions to preallocate the data.
structs=[];enuminfo=[];fcnNum=1;
fcns=struct('name',ival,'calltype',ival,'LHS',ival,'RHS',ival,'alias',ival,'thunkname', ival);
MfilePath=fileparts(mfilename('fullpath'));
ThunkLibName=fullfile(MfilePath,'kernel32_thunk_pcwin64');
% DWORD __stdcall GetFullPathNameW ( LPCWSTR , DWORD , LPWSTR , LPWSTR *); 
fcns.thunkname{fcnNum}='ulongvoidPtrulongvoidPtrvoidPtrThunk';fcns.name{fcnNum}='GetFullPathNameW'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='ulong'; fcns.RHS{fcnNum}={'uint16Ptr', 'ulong', 'uint16Ptr', 'uint16PtrPtr'};fcnNum=fcnNum+1;
% DWORD __stdcall GetFullPathNameA ( LPCSTR , DWORD , LPSTR , LPSTR *); 
fcns.thunkname{fcnNum}='ulongcstringulongcstringvoidPtrThunk';fcns.name{fcnNum}='GetFullPathNameA'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='ulong'; fcns.RHS{fcnNum}={'cstring', 'ulong', 'cstring', 'cstringPtr'};fcnNum=fcnNum+1;
% DWORD __stdcall GetLongPathNameW ( LPCWSTR , LPWSTR , DWORD ); 
fcns.thunkname{fcnNum}='ulongvoidPtrvoidPtrulongThunk';fcns.name{fcnNum}='GetLongPathNameW'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='ulong'; fcns.RHS{fcnNum}={'uint16Ptr', 'uint16Ptr', 'ulong'};fcnNum=fcnNum+1;
methodinfo=fcns;